import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { QueryProvider } from './providers/query-provider'
import { AppShell } from './AppShell'
import { DEFAULT_LOCALE } from '@/shared/lib/i18n/config'

const interSans = Inter({
  variable: '--font-inter',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Snaptix',
  description: 'Generated by create Snaptix',
}

// Layout не читает cookies/headers на сервере — иначе всё приложение стало бы
// динамическим и главная не смогла бы быть SSG. Язык применяется на клиенте
// в TranslationsProvider, поэтому здесь рендерим дефолтную локаль.
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang={DEFAULT_LOCALE}>
      <body className={interSans.variable}>
        <QueryProvider>
          <AppShell>{children}</AppShell>
        </QueryProvider>
      </body>
    </html>
  )
}